apiVersion: v1
kind: Service
metadata:
  name: infographic-api
  namespace: orion
  labels:
    app.kubernetes.io/name: infographic-api
    app.kubernetes.io/part-of: orion
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: infographic-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
